# Generated by Django 4.2.7 on 2023-11-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Review', '0002_alter_prod_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod_review',
            name='avg_rating',
            field=models.IntegerField(default=0),
        ),
    ]
