# Generated by Django 4.2.7 on 2023-11-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Review', '0006_alter_prod_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod_review',
            name='rating',
            field=models.CharField(choices=[('★', '★'), ('★★', '★★'), ('★★★', '★★★'), ('★★★★', '★★★★'), ('★★★★★', '★★★★★')], max_length=5),
        ),
    ]
