# Generated by Django 4.2.7 on 2023-11-24 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_category_category_pic'),
        ('Review', '0009_alter_prod_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prod_review',
            name='avg_rating',
        ),
        migrations.CreateModel(
            name='prod_avg_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_rating', models.IntegerField(default=0)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.product')),
            ],
        ),
    ]
