# Generated by Django 4.2.7 on 2023-11-24 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Review', '0010_remove_prod_review_avg_rating_prod_avg_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod_review',
            name='int_rating',
            field=models.IntegerField(default=0),
        ),
    ]
