# Generated by Django 4.2.7 on 2023-11-29 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.IntegerField()),
                ('item', models.CharField(max_length=200)),
                ('qyt', models.IntegerField()),
                ('price', models.FloatField()),
                ('total', models.FloatField()),
                ('order_at', models.DateField(auto_now_add=True)),
                ('order_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.cart_order')),
            ],
        ),
    ]
