# Generated by Django 4.2.7 on 2023-12-01 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='order_items',
            new_name='order_by_user',
        ),
    ]
