# Generated by Django 4.2.7 on 2023-11-19 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('short_details', models.TextField()),
                ('quantity', models.PositiveIntegerField()),
                ('prod_img', models.ImageField(upload_to='product_img/')),
                ('sub_prod_img1', models.ImageField(upload_to='product_img/sub_prod_img/')),
                ('sub_prod_img2', models.ImageField(upload_to='product_img/sub_prod_img/')),
                ('sub_prod_img3', models.ImageField(upload_to='product_img/sub_prod_img/')),
                ('description', models.TextField()),
                ('featured_prod', models.BooleanField(default=False)),
                ('New_arrivals', models.BooleanField(default=False)),
                ('Best_selling_prod', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.category')),
            ],
        ),
    ]
