# Generated by Django 4.2.7 on 2023-11-25 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_category_category_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avg_rating_star',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
