# Generated by Django 4.2.7 on 2023-11-25 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_product_avg_rating_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avg_rating',
            field=models.IntegerField(default=0),
        ),
    ]
